---
- name: Check password
  command: mysql -e ';'
  register: _check_password
  changed_when: false
  failed_when: false

- name: Set the MySQL root password
  command: 'mysqladmin -u root password "{{ openio_galera_root_password }}"'
  changed_when: false
  when: _check_password.rc == 0
  ignore_errors: "{{ ansible_check_mode }}"

- name: Delete anonymous connections
  mysql_user:
    login_user: "{{ openio_galera_root_user }}"
    login_password: "{{ openio_galera_root_password }}"
    name: ""
    state: absent
    login_unix_socket: "{{ openio_galera_socket }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Secure the MySQL root user for localhost"
  mysql_user:
    login_user: "{{ openio_galera_root_user }}"
    login_password: "{{ openio_galera_root_password }}"
    name: "{{ openio_galera_root_user }}"
    host: "{{ item }}"
    login_unix_socket: "{{ openio_galera_socket }}"
  with_items:
    - "::1"
    - "127.0.0.1"
    - "localhost"
    #- "{{ openio_galera_bind_address }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Remove the MySQL test database
  mysql_db:
    db: test
    login_user: "{{ openio_galera_root_user }}"
    login_password: "{{ openio_galera_root_password }}"
    state: absent
    login_unix_socket: "{{ openio_galera_socket }}"
  ignore_errors: "{{ ansible_check_mode }}"
...
