---
- name: Check password
  command: mysql -e ';'
  register: _check_password
  changed_when: false
  failed_when: false

- name: Set the MySQL root password
  command: 'mysqladmin -u root password "{{ openio_galera_root_password }}"'
  changed_when: false
  when: _check_password.rc == 0

- name: Delete anonymous connections
  mysql_user:
    login_user: "{{ openio_galera_root_user }}"
    login_password: "{{ openio_galera_root_password }}"
    name: ""
    host_all: true
    state: absent

- name: "Secure the MySQL root user for localhost"
  mysql_user:
    login_user: "{{ openio_galera_root_user }}"
    login_password: "{{ openio_galera_root_password }}"
    name: "{{ openio_galera_root_user }}"
    host: "{{ item }}"
  with_items:
    - "::1"
    - "127.0.0.1"
    - "localhost"
    #- "{{ openio_galera_bind_address }}"

- name: Remove the MySQL test database
  mysql_db:
    db: test
    login_user: "{{ openio_galera_root_user }}"
    login_password: "{{ openio_galera_root_password }}"
    state: absent
...
